"use client"

import { useMemo } from "react"

import { icfCoreSet } from "@/core/assessment/icf-codes"
import { cn } from "@/lib/utils"
import { Badge } from "@/components/ui/badge"
import { useLanguage } from "@/components/language-provider"

type IcfCategoryKey = "b" | "d" | "e"

export type IcfAnalysisBuckets = {
  b?: string[]
  d?: string[]
  e?: string[]
}

type CategoryMeta = {
  key: IcfCategoryKey
  label: string
  accentClass: string
  badgeClass: string
}

const CATEGORY_STYLES: Record<IcfCategoryKey, Omit<CategoryMeta, "label"> & { label?: string }> = {
  b: {
    key: "b",
    accentClass: "from-sky-500/15 to-sky-500/5 border-sky-200/60 text-sky-900 dark:text-sky-200",
    badgeClass: "bg-sky-100 text-sky-800 dark:bg-sky-900/40 dark:text-sky-100",
  },
  d: {
    key: "d",
    accentClass:
      "from-emerald-500/15 to-emerald-500/5 border-emerald-200/60 text-emerald-900 dark:text-emerald-200",
    badgeClass: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-100",
  },
  e: {
    key: "e",
    accentClass:
      "from-amber-500/15 to-amber-500/5 border-amber-200/60 text-amber-900 dark:text-amber-200",
    badgeClass: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-100",
  },
}

const findIcfMeta = (code: string) => icfCoreSet.find((item) => item.code.toLowerCase() === code.toLowerCase())

export function IcfVisualization({ data }: { data: IcfAnalysisBuckets | null }) {
  const { t } = useLanguage()

  const categories = useMemo(() => {
    if (!data) return []
    return (["b", "d", "e"] as IcfCategoryKey[])
      .map((key) => {
        const codes = data[key] ?? []
        return {
          ...CATEGORY_STYLES[key],
          label:
            key === "b"
              ? t("icfVisualization.category.body")
              : key === "d"
                ? t("icfVisualization.category.activity")
                : t("icfVisualization.category.environment"),
          codes,
        }
      })
      .filter((category) => category.codes.length > 0)
  }, [data, t])

  const totalCodes = categories.reduce((acc, category) => acc + category.codes.length, 0)
  const confidenceScore = Math.min(95, 65 + totalCodes * 8)

  if (!data || categories.length === 0) {
    return null
  }

  return (
    <section className="rounded-2xl border border-border bg-card/80 p-6 shadow-sm backdrop-blur-sm">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            {t("icfVisualization.subtitle")}
          </p>
          <h2 className="text-xl font-semibold text-foreground">{t("icfVisualization.title")}</h2>
        </div>
        <div className="flex items-center gap-3">
          <div className="text-right">
            <p className="text-xs text-muted-foreground">{t("icfVisualization.confidenceLabel")}</p>
            <p className="text-lg font-semibold text-primary">{confidenceScore}%</p>
          </div>
          <Badge variant="outline" className="text-xs uppercase">
            {t("icfVisualization.autoGenerated")}
          </Badge>
        </div>
      </div>

      <p className="mt-3 text-sm text-muted-foreground">{t("icfVisualization.description")}</p>

      <div className="mt-6 space-y-6">
        {categories.map((category) => (
          <div
            key={category.key}
            className={cn(
              "rounded-2xl border bg-linear-to-br p-4 transition hover:shadow-md",
              category.accentClass,
            )}
          >
            <div className="mb-4 flex items-center gap-3">
              <span className={cn("rounded-full px-3 py-1 text-xs font-semibold", category.badgeClass)}>
                {category.label}
              </span>
              <span className="text-xs text-muted-foreground">
                {t("icfVisualization.codesCount", { count: category.codes.length })}
              </span>
            </div>

            <div className="space-y-3">
              {category.codes.map((code) => {
                const meta = findIcfMeta(code)
                return (
                  <div key={`${category.key}-${code}`} className="rounded-xl border border-border/60 bg-background/80 p-4">
                    <div className="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <p className="text-base font-semibold text-foreground">
                          {code.toUpperCase()}
                          {meta ? ` · ${meta.description}` : ""}
                        </p>
                        {!meta && (
                          <p className="text-sm text-muted-foreground">
                            {t("icfVisualization.unknownCode")}
                          </p>
                        )}
                      </div>
                      <Badge variant="secondary" className="text-xs uppercase tracking-wide">
                        {category.key}
                      </Badge>
                    </div>

                    {meta?.isoHints?.length ? (
                      <div className="mt-3 text-sm text-muted-foreground">
                        <p className="mb-1 font-medium text-foreground/80">
                          {t("icfVisualization.isoHints")}
                        </p>
                        <div className="flex flex-wrap gap-2">
                          {meta.isoHints.map((hint) => (
                            <span
                              key={`${code}-${hint}`}
                              className="rounded-full border border-dashed border-border/80 bg-background px-3 py-1 text-xs font-medium"
                            >
                              ISO {hint}
                            </span>
                          ))}
                        </div>
                      </div>
                    ) : null}
                  </div>
                )
              })}
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}

